data:
  filepath: "D:/Cursos/Maestria - IA Aplicada/MLOps/Proyecto/github/MLOPS-MNA-Equipo-17/data1/raw/TCGA_GBM_LGG_Mutations_all.csv"
  processed: data1/processed/
  models: models/
  reports: reports/

models:
  decision_tree:
    max_depth: 5
    random_state: 42
    criterion: "entropy"
  logistic_regression:
    C: 1.0
    solver: "liblinear"
    random_state: 42
  random_forest:
    n_estimators: 100
    max_depth: 5
    random_state: 42

mlflow:
  experiment_name: "Tumor_Classification"
  tracking_uri: "http://127.0.0.1:5000"
